import { Report, TeamMember, Alumni, Event } from './types';

// Placeholder reports data
export const reports: Report[] = [
  {
    id: 'eq-001',
    date: '2024-11-15',
    title: 'Sector Analysis: European Luxury Goods',
    description: 'Comprehensive analysis of the European luxury sector with focus on key market drivers and valuation metrics.',
    division: 'equity',
    pdfUrl: '#',
  },
  {
    id: 'eq-002',
    date: '2024-10-28',
    title: 'Company Initiation: Industrial Manufacturing',
    description: 'Initiation of coverage on a leading industrial manufacturing company with detailed financial modelling.',
    division: 'equity',
    pdfUrl: '#',
  },
  {
    id: 'eq-003',
    date: '2024-09-12',
    title: 'Thematic Research: Energy Transition',
    description: 'Analysis of investment implications from the ongoing energy transition across European markets.',
    division: 'equity',
    pdfUrl: '#',
  },
  {
    id: 'inv-001',
    date: '2024-11-20',
    title: 'Private Market Opportunities: Q4 2024',
    description: 'Quarterly review of private equity and venture capital opportunities in the European market.',
    division: 'investment',
    pdfUrl: '#',
  },
  {
    id: 'inv-002',
    date: '2024-10-05',
    title: 'M&A Analysis: Technology Sector',
    description: 'Detailed analysis of recent merger and acquisition activity in the technology sector.',
    division: 'investment',
    pdfUrl: '#',
  },
  {
    id: 'mac-001',
    date: '2024-11-18',
    title: 'Monthly Macro Commentary',
    description: 'Analysis of global macroeconomic trends and their implications for asset allocation.',
    division: 'macro',
    pdfUrl: '#',
  },
  {
    id: 'mac-002',
    date: '2024-10-15',
    title: 'Central Bank Watch: ECB Policy Outlook',
    description: 'Deep dive into European Central Bank monetary policy trajectory and market implications.',
    division: 'macro',
    pdfUrl: '#',
  },
  {
    id: 'mac-003',
    date: '2024-09-20',
    title: 'Inflation Dynamics: A Structural View',
    description: 'Long-term analysis of inflation drivers and their persistence in developed markets.',
    division: 'macro',
    pdfUrl: '#',
  },
  {
    id: 'pm-ls-001',
    date: '2024-11-01',
    title: 'Long Short Equity Fund: Monthly Report',
    description: 'Performance review and portfolio positioning for the Long Short Equity Fund.',
    division: 'portfolio',
    fund: 'long-short',
    pdfUrl: '#',
  },
  {
    id: 'pm-ls-002',
    date: '2024-10-01',
    title: 'Long Short Equity Fund: Monthly Report',
    description: 'Performance review and portfolio positioning for the Long Short Equity Fund.',
    division: 'portfolio',
    fund: 'long-short',
    pdfUrl: '#',
  },
  {
    id: 'pm-ma-001',
    date: '2024-11-01',
    title: 'Multi Asset Fund: Monthly Report',
    description: 'Performance review and asset allocation update for the Multi Asset Global Opportunities Fund.',
    division: 'portfolio',
    fund: 'multi-asset',
    pdfUrl: '#',
  },
  {
    id: 'pm-dps-001',
    date: '2023-06-01',
    title: 'DPS Fund: Final Report',
    description: 'Final performance report for the Diversified Passive Selection Fund.',
    division: 'portfolio',
    fund: 'dps',
    pdfUrl: '#',
  },
  {
    id: 'pm-pir-001',
    date: '2022-12-01',
    title: 'Italian Equity PIR: Final Report',
    description: 'Final performance report for the Italian Equity PIR Fund.',
    division: 'portfolio',
    fund: 'pir',
    pdfUrl: '#',
  },
  {
    id: 'qt-001',
    date: '2024-11-10',
    title: 'Factor Analysis: Momentum Strategies',
    description: 'Quantitative analysis of momentum factor performance across global equity markets.',
    division: 'quant',
    pdfUrl: '#',
  },
  {
    id: 'qt-002',
    date: '2024-09-25',
    title: 'Machine Learning in Portfolio Construction',
    description: 'Research on the application of machine learning techniques in systematic portfolio management.',
    division: 'quant',
    pdfUrl: '#',
  },
];

// Placeholder team members data
export const teamMembers: TeamMember[] = [
  // Board
  {
    id: 'tm-001',
    name: 'Placeholder',
    surname: 'President',
    position: 'President',
    isBoard: true,
    linkedinUrl: '#',
  },
  {
    id: 'tm-002',
    name: 'Placeholder',
    surname: 'Vice President',
    position: 'Vice President',
    isBoard: true,
    linkedinUrl: '#',
  },
  {
    id: 'tm-003',
    name: 'Placeholder',
    surname: 'Asset Manager',
    position: 'Head of Asset Management',
    isBoard: true,
    linkedinUrl: '#',
  },
  // Division Heads
  {
    id: 'tm-004',
    name: 'Placeholder',
    surname: 'Equity Head',
    position: 'Head of Equity Research',
    division: 'equity',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-005',
    name: 'Placeholder',
    surname: 'Investment Head',
    position: 'Head of Investment Research',
    division: 'investment',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-006',
    name: 'Placeholder',
    surname: 'Macro Head',
    position: 'Head of Macro Research',
    division: 'macro',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-007',
    name: 'Placeholder',
    surname: 'Portfolio Head',
    position: 'Head of Portfolio Management',
    division: 'portfolio',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-008',
    name: 'Placeholder',
    surname: 'Quant Head',
    position: 'Head of Quant Research',
    division: 'quant',
    isBoard: false,
    linkedinUrl: '#',
  },
  // Portfolio Managers
  {
    id: 'tm-009',
    name: 'Placeholder',
    surname: 'PM Long Short',
    position: 'Portfolio Manager',
    division: 'portfolio',
    fund: 'long-short',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-010',
    name: 'Placeholder',
    surname: 'PM Multi Asset',
    position: 'Portfolio Manager',
    division: 'portfolio',
    fund: 'multi-asset',
    isBoard: false,
    linkedinUrl: '#',
  },
  // Analysts - Equity
  {
    id: 'tm-011',
    name: 'Placeholder',
    surname: 'Senior Equity',
    position: 'Senior Analyst',
    division: 'equity',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-012',
    name: 'Placeholder',
    surname: 'Analyst Equity',
    position: 'Analyst',
    division: 'equity',
    isBoard: false,
    linkedinUrl: '#',
  },
  // Analysts - Investment
  {
    id: 'tm-013',
    name: 'Placeholder',
    surname: 'Senior Investment',
    position: 'Senior Analyst',
    division: 'investment',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-014',
    name: 'Placeholder',
    surname: 'Analyst Investment',
    position: 'Analyst',
    division: 'investment',
    isBoard: false,
    linkedinUrl: '#',
  },
  // Analysts - Macro
  {
    id: 'tm-015',
    name: 'Placeholder',
    surname: 'Senior Macro',
    position: 'Senior Analyst',
    division: 'macro',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-016',
    name: 'Placeholder',
    surname: 'Analyst Macro',
    position: 'Analyst',
    division: 'macro',
    isBoard: false,
    linkedinUrl: '#',
  },
  // Analysts - Quant
  {
    id: 'tm-017',
    name: 'Placeholder',
    surname: 'Senior Quant',
    position: 'Senior Analyst',
    division: 'quant',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-018',
    name: 'Placeholder',
    surname: 'Analyst Quant',
    position: 'Analyst',
    division: 'quant',
    isBoard: false,
    linkedinUrl: '#',
  },
  // Operations & Media
  {
    id: 'tm-019',
    name: 'Placeholder',
    surname: 'Operations Head',
    position: 'Head of Operations',
    isBoard: false,
    linkedinUrl: '#',
  },
  {
    id: 'tm-020',
    name: 'Placeholder',
    surname: 'Media Head',
    position: 'Head of Media',
    isBoard: false,
    linkedinUrl: '#',
  },
];

// Placeholder alumni data
export const alumni: Alumni[] = [
  {
    id: 'al-001',
    name: 'Placeholder',
    surname: 'Alumni One',
    graduationYear: 2023,
    currentRole: 'Investment Analyst',
    company: 'Global Investment Bank',
    linkedinUrl: '#',
  },
  {
    id: 'al-002',
    name: 'Placeholder',
    surname: 'Alumni Two',
    graduationYear: 2023,
    currentRole: 'Associate',
    company: 'Private Equity Firm',
    linkedinUrl: '#',
  },
  {
    id: 'al-003',
    name: 'Placeholder',
    surname: 'Alumni Three',
    graduationYear: 2022,
    currentRole: 'Quantitative Researcher',
    company: 'Hedge Fund',
    linkedinUrl: '#',
  },
  {
    id: 'al-004',
    name: 'Placeholder',
    surname: 'Alumni Four',
    graduationYear: 2022,
    currentRole: 'Strategy Consultant',
    company: 'Consulting Firm',
    linkedinUrl: '#',
  },
  {
    id: 'al-005',
    name: 'Placeholder',
    surname: 'Alumni Five',
    graduationYear: 2021,
    currentRole: 'Portfolio Manager',
    company: 'Asset Management Company',
    linkedinUrl: '#',
  },
  {
    id: 'al-006',
    name: 'Placeholder',
    surname: 'Alumni Six',
    graduationYear: 2021,
    currentRole: 'Research Associate',
    company: 'Equity Research Firm',
    linkedinUrl: '#',
  },
  {
    id: 'al-007',
    name: 'Placeholder',
    surname: 'Alumni Seven',
    graduationYear: 2020,
    currentRole: 'Vice President',
    company: 'Investment Bank',
    linkedinUrl: '#',
  },
  {
    id: 'al-008',
    name: 'Placeholder',
    surname: 'Alumni Eight',
    graduationYear: 2020,
    currentRole: 'Founder',
    company: 'FinTech Startup',
    linkedinUrl: '#',
  },
];

// Placeholder events data
export const events: Event[] = [
  {
    id: 'ev-001',
    date: '2024-12-05',
    title: 'Annual Investment Conference',
    location: 'Bocconi University, Milan',
    description: 'Our flagship annual event featuring industry speakers and networking opportunities with professionals from leading financial institutions.',
  },
  {
    id: 'ev-002',
    date: '2024-11-15',
    title: 'Macro Outlook 2025',
    location: 'Virtual Event',
    description: 'Presentation of our macroeconomic outlook for the coming year, covering global growth, inflation, and monetary policy.',
  },
  {
    id: 'ev-003',
    date: '2024-10-20',
    title: 'Private Equity Workshop',
    location: 'Bocconi University, Milan',
    description: 'Interactive workshop on private equity valuation methodologies and deal structuring.',
  },
  {
    id: 'ev-004',
    date: '2024-09-28',
    title: 'Quantitative Finance Seminar',
    location: 'Bocconi University, Milan',
    description: 'Technical seminar on quantitative strategies and systematic investing approaches.',
  },
  {
    id: 'ev-005',
    date: '2024-05-10',
    title: 'Equity Research Masterclass',
    location: 'Bocconi University, Milan',
    description: 'Intensive session on equity research methodologies, financial modelling, and valuation techniques.',
  },
];

// Key figures for homepage
export const keyFigures = {
  totalReports: reports.length,
  totalMembers: teamMembers.length,
  totalAlumni: alumni.length,
};
