project_id = "asjudzdgsccacpjbzsue"

[functions.admin-auth]
verify_jwt = false

[functions.admin-events]
verify_jwt = false

[functions.admin-files]
verify_jwt = false

[functions.admin-team]
verify_jwt = false

[functions.admin-alumni]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
