project_id = "asjudzdgsccacpjbzsue"

[functions.admin-auth]
verify_jwt = false

[functions.admin-events]
verify_jwt = false

[functions.admin-files]
verify_jwt = false

[functions.admin-team]
verify_jwt = false