// =====================================================================
// Regenerate public/sitemap.xml from the route registry.
// ---------------------------------------------------------------------
//   node scripts/generate-sitemap.mjs
//
// It reads the same list of routes that supplies every page's title and
// description (src/lib/seo/routes.ts), so the sitemap cannot fall behind
// the site: a page that has been described has an entry, and a page that
// has been removed loses one.
//
// It is DELIBERATELY NOT WIRED INTO THE BUILD. The build is what deploys
// this site, and adding a step to it that can fail is a poor trade for a
// file that changes when a route is added, which is a handful of times a
// year. Run it by hand when routes change, and commit the result.
//
// The registry is TypeScript, so rather than compiling it this script
// parses the object literals out of the source. That sounds fragile and
// is: it is guarded by an assertion on the number of routes found, so a
// change in the file's shape fails loudly here rather than silently
// producing a half-empty sitemap.
// =====================================================================

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const SITE_URL = (process.env.VITE_SITE_URL || 'https://minervaims.org').replace(/\/+$/, '');
const source = readFileSync(resolve(root, 'src/lib/seo/routes.ts'), 'utf8');

/** Pull `'/path': { … }` blocks out of one exported map. */
function parseMap(name) {
  const start = source.indexOf(`export const ${name}`);
  if (start === -1) throw new Error(`Could not find ${name} in routes.ts`);
  const open = source.indexOf('{', start);
  let depth = 0;
  let end = open;
  for (let i = open; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') { depth--; if (depth === 0) { end = i; break; } }
  }
  const body = source.slice(open + 1, end);

  const entries = [];
  // Keys are quoted when they contain a slash or a hyphen ('/about',
  // 'multi-asset') and bare when they are plain identifiers (equity, dps).
  // Both forms appear in this file, so both are matched.
  const keyRe = /(?:^|\n)\s{2}(?:'([^']+)'|([A-Za-z_$][\w$]*)):\s*\{/g;
  let m;
  while ((m = keyRe.exec(body)) !== null) {
    const key = m[1] ?? m[2];
    // The entry's own braces, so a nested object cannot end it early.
    let d = 0, i = m.index + m[0].length - 1, stop = i;
    for (; i < body.length; i++) {
      if (body[i] === '{') d++;
      else if (body[i] === '}') { d--; if (d === 0) { stop = i; break; } }
    }
    const block = body.slice(m.index, stop);
    entries.push({
      key,
      noindex: /noindex:\s*true/.test(block),
      priority: (block.match(/priority:\s*([\d.]+)/) || [])[1],
      changefreq: (block.match(/changefreq:\s*'([a-z]+)'/) || [])[1],
    });
  }
  return entries;
}

const routes = parseMap('ROUTE_META');
const divisions = parseMap('DIVISION_META');
const funds = parseMap('FUND_META');

// Loud rather than silent: these numbers only ever grow.
if (routes.length < 15) throw new Error(`Only ${routes.length} routes parsed; routes.ts shape has changed.`);
if (divisions.length !== 5) throw new Error(`Expected 5 divisions, parsed ${divisions.length}.`);
if (funds.length !== 4) throw new Error(`Expected 4 funds, parsed ${funds.length}.`);

const urls = [
  ...routes
    .filter((r) => !r.noindex && r.priority)
    .map((r) => ({ path: r.key, priority: Number(r.priority), changefreq: r.changefreq || 'monthly' })),
  ...divisions.map((d) => ({ path: `/divisions/${d.key}`, priority: Number(d.priority || 0.8), changefreq: 'monthly' })),
  ...funds.map((f) => ({ path: `/funds/${f.key}`, priority: Number(f.priority || 0.7), changefreq: 'monthly' })),
].sort((a, b) => b.priority - a.priority || a.path.localeCompare(b.path));

const today = new Date().toISOString().slice(0, 10);
const body = urls
  .map(({ path, priority, changefreq }) => [
    '  <url>',
    `    <loc>${SITE_URL}${path === '/' ? '/' : path}</loc>`,
    `    <lastmod>${today}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority.toFixed(1)}</priority>`,
    '  </url>',
  ].join('\n'))
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/generate-sitemap.mjs from src/lib/seo/routes.ts.
  Run "node scripts/generate-sitemap.mjs" after adding or removing a route.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync(resolve(root, 'public/sitemap.xml'), xml, 'utf8');
console.log(`sitemap.xml written with ${urls.length} URLs at ${SITE_URL}`);
